<a href="https://colab.research.google.com/github/bebelana/analiseDadosPandas/blob/main/aula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manipulação de dados com o Pandas

Autor: Ana Izabel

Data: 08/02/2023

In [1]:
# Importando biblioteca pandas do python
import pandas as pd

In [2]:
# Carregando um conjunto de dados
df = pd.read_excel("/ca-2021-02.xlsx")

In [10]:
# Utilizando colunas especificas 
columns_df = df[['Revenda', 'Municipio','Produto', 'Valor de Venda', 'Bairro']]
display(columns_df)

,Revenda,Municipio,Produto,Valor de Venda,Bairro
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799,CANAFISTULA
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299,CANAFISTULA
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549,CANAFISTULA
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899,CANAFISTULA
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649,CANAFISTULA
...,...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859,TROPICAL
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580,ALVORADA
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740,ALVORADA
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448,ALVORADA
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580,ALVORADA

In [11]:
# Filtrando por uma condicao, buscando por postos de BH com gasolina
gasolinaBH_df = columns_df.loc[(columns_df['Municipio'] == 'BELO HORIZONTE') & (columns_df['Produto'] == 'GASOLINA')]
display(gasolinaBH_df)

,Revenda,Municipio,Produto,Valor de Venda,Bairro
12198,POSTO TUNEL LTDA,BELO HORIZONTE,GASOLINA,6.785,FLORESTA
12201,POSTO CN LTDA,BELO HORIZONTE,GASOLINA,6.774,DA GRACA
12206,POSTO MINAS SHOPPING LTDA,BELO HORIZONTE,GASOLINA,6.775,UNIAO
12209,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,BELO HORIZONTE,GASOLINA,6.790,PALMARES
12212,POSTO DO PAPAI LTDA,BELO HORIZONTE,GASOLINA,6.845,FLORESTA
...,...,...,...,...,...
165348,POSTO R.E.M. LTDA,BELO HORIZONTE,GASOLINA,6.759,BARRO PRETO
166200,POSTO PARQUE LTDA,BELO HORIZONTE,GASOLINA,6.749,SANTA CRUZ
166318,POSTO ZEPPELIN LTDA,BELO HORIZONTE,GASOLINA,6.755,PADRE EUSTAQUIO
166508,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
166545,POSTO FLORESTA LTDA.,BELO HORIZONTE,GASOLINA,6.744,FLORESTA

In [6]:
#nova informação a partir de uma coluna existente
gasolinaBH_df['Imposto'] = gasolinaBH_df['Valor de Venda'] * 0.10
display(gasolinaBH_df)

<ipython-input-6-6e7f63d2a113>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gasolinaBH_df['Imposto'] = gasolinaBH_df['Valor de Venda'] * 0.10

,Revenda,Municipio,Produto,Valor de Venda,Imposto
12198,POSTO TUNEL LTDA,BELO HORIZONTE,GASOLINA,6.785,0.6785
12201,POSTO CN LTDA,BELO HORIZONTE,GASOLINA,6.774,0.6774
12206,POSTO MINAS SHOPPING LTDA,BELO HORIZONTE,GASOLINA,6.775,0.6775
12209,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,BELO HORIZONTE,GASOLINA,6.790,0.6790
12212,POSTO DO PAPAI LTDA,BELO HORIZONTE,GASOLINA,6.845,0.6845
...,...,...,...,...,...
165348,POSTO R.E.M. LTDA,BELO HORIZONTE,GASOLINA,6.759,0.6759
166200,POSTO PARQUE LTDA,BELO HORIZONTE,GASOLINA,6.749,0.6749
166318,POSTO ZEPPELIN LTDA,BELO HORIZONTE,GASOLINA,6.755,0.6755
166508,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.755,0.6755
166545,POSTO FLORESTA LTDA.,BELO HORIZONTE,GASOLINA,6.744,0.6744

In [9]:
# Ordernar o data frame pela coluna valor de venda
display(gasolinaBH_df.sort_values(by='Valor de Venda', ascending=True))

,Revenda,Municipio,Produto,Valor de Venda,Imposto
13860,POSTO OLIMAR COMERCIO DE COMBUSTIVEIS LTDA,BELO HORIZONTE,GASOLINA,6.675,0.6675
12241,POSTO QUICK LTDA,BELO HORIZONTE,GASOLINA,6.675,0.6675
12251,POSTO PIO XII LTDA.,BELO HORIZONTE,GASOLINA,6.685,0.6685
164145,POSTO BOM BOM LTDA,BELO HORIZONTE,GASOLINA,6.739,0.6739
164115,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,BELO HORIZONTE,GASOLINA,6.740,0.6740
...,...,...,...,...,...
128967,POSTO BRUNATA LTDA,BELO HORIZONTE,GASOLINA,6.999,0.6999
49626,POSTO COELHO LTDA,BELO HORIZONTE,GASOLINA,6.999,0.6999
69751,POSTO COELHO LTDA,BELO HORIZONTE,GASOLINA,6.999,0.6999
31261,POSTO COELHO LTDA,BELO HORIZONTE,GASOLINA,6.999,0.6999
145014,POSTO COELHO LTDA,BELO HORIZONTE,GASOLINA,6.999,0.6999

In [27]:
gasolinaBH_df.loc[(gasolinaBH_df['Bairro'] == 'PRADO')]

,Revenda,Municipio,Produto,Valor de Venda,Bairro
12230,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.785,PRADO
15733,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.785,PRADO
31239,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.885,PRADO
34401,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.895,PRADO
49604,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.885,PRADO
52445,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.885,PRADO
69729,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.885,PRADO
72485,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.885,PRADO
87605,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.775,PRADO
90345,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.795,PRADO
124787,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
127536,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
144999,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
147389,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
164132,POSTO PHOENIX LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO
166508,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,BELO HORIZONTE,GASOLINA,6.755,PRADO

In [51]:
# Media da Gasolina e Gasolina Aditivada de BH no bairro Prado
df.loc[((df['Produto'] == 'GASOLINA') | (df['Produto'] == 'GASOLINA ADITIVADA'))  &
       (df['Bairro'] == 'PRADO') &
       (df['Municipio']=='BELO HORIZONTE'), ['Valor de Venda']].mean().round(2)

Valor de Venda    6.96
dtype: float64

In [66]:
# como mostrar media de valor de venda por combustivel
media_produto = columns_df[['Produto', 'Valor de Venda']].groupby('Produto').mean()
display(media_produto.style.format("{:.2f}"))

In [67]:
# Quero adicionar uma coluna de valor booleano no combustiveis_df 
# Chamada "Ativo" que, por padrão, vai ser True para 
# TODAS as linhas
df['Ativo'] = True
print(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [72]:
df['Obs'] = ["Melhor Estado" if municipio == 'MG' else '' for municipio in df['Estado - Sigla']]

In [73]:
# Exportar para excel
gasolinaBH_df.to_excel("gasolinaBH_df.xlsx")